# got from sample https://docs.docker.com/samples/rails/
FROM ruby:2.6
ENV RAILS_ENV production
ENV BUNDLE_WITHOUT development:test
RUN apt-get update -qq && apt-get install -y nodejs mariadb-client
WORKDIR /guteam
COPY ./guteam /guteam
RUN bundle install

COPY ./guteam/entrypoint.sh /usr/bin/
RUN rails db:migrate
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]