name: Build React on S3
on:
  push:
      branches:
        - main
env:
  NODE_VERSION: '14.x' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Change Dir
        run: cd ./docker-codes/http-server/guteam
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GUTEAM_S3: ${{ secrets.GUTEAM_S3 }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 ./build s3://$GUTEAM_S3
      - name: Clear Cache
        env:
          CLOUD_FRONT_DID: ${{ secrets.CLOUD_FRONT_DID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DID --paths "/*"
