name: React CI/CD
on:
  push:
      branches:
        - main
      paths:
        - 'docker-codes/http-server/**'
env:
  NODE_VERSION: '14.x' 

jobs:
  react-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install Dependencies
        run: cd ./docker-codes/http-server/guteam && yarn install
        
      - name: Create dotenv file
        run: |
          cd ./docker-codes/http-server/guteam
          touch .env
          echo "REACT_APP_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "REACT_APP_AUTH0_AUDIENCE=${{ secrets.REACT_APP_AUTH0_AUDIENCE }}" >> .env
          echo "REACT_APP_AUTH0_CLIENT_ID=${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}" >> .env
          echo "REACT_APP_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }}" >> .env
          echo "REACT_APP_INITIAL_AVATAR=${{ secrets.REACT_APP_INITIAL_AVATAR }}" >> .env
          echo "REACT_APP_REGION=${{ secrets.REACT_APP_REGION }}" >> .env
          echo "REACT_APP_REST_URL=${{ secrets.REACT_APP_REST_URL }}" >> .env
          echo "REACT_APP_S3_BUCKET=${{ secrets.REACT_APP_S3_BUCKET }}" >> .env
          echo "REACT_APP_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_SECRET_ACCESS_KEY }}" >> .env
      
      - name: Build
        run: cd ./docker-codes/http-server/guteam && yarn build
        
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GUTEAM_S3: ${{ secrets.GUTEAM_S3 }}
        run: |
          cd ./docker-codes/http-server/guteam && aws s3 cp --recursive --region ap-northeast-1 ./build s3://$GUTEAM_S3
          
      - name: Clear CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v1.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
